server:
  port: 8087

spring:
  application:
    name: delay1-exchange
  rabbitmq:
    host: 192.168.250.78
    port: 5672
    username: guest
    password: guest
    virtual-host: powernode

custom:
  exchangeName: exchange.delay.2
  queueNormalName: queue.delay.normal.2
  queueDlxName: queue.delay.dlx.2
