server:
  port: 8089

spring:
  application:
    name: return1-exchange
  rabbitmq:
    host: 192.168.250.78
    port: 5672
    username: guest
    password: guest
    virtual-host: powernode

custom:
  exchangeName: exchange.return.1
  queueName: queue.return.1
